services:
  db:
    build: ./db
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3308:3308
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    volumes:
      - $PWD/backend/internal:/go/src/app/internal 
    ports:
      - 8000:8000
    stdin_open: true

volumes:
  mysql_data: